export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { Services } from './Services'
export { About } from './About'
export { Portfolio } from './Portfolio'
export { Testimonials } from './Testimonials'
export { Contact } from './Contact'
export { Footer } from './Footer'
